### ISSUE TITLE
Feature request: more whiskers

### ISSUE THREAD

**Issue by dvalters** [simon-m-mudd/cat_on_rollerskates_opendata#1]
On my system, the cat renders with only three whiskers.

Steps to reproduce:
- Open cat file png
- Focus eyes on picture
- Note the number of whiskers.

System:
Linux Fedora 24

**Comment by simon-m-mudd** [comment]
Cats have more than 3 whiskers?

**Comment by fclubb** [comment]
@dvalters have you tried deleting all of the .o, .out, and .exe files and recompiling?

**Comment by dvalters** [comment]
@fclubb I tried the `cat` command but nothing happened. That is a good suggestion though I will retry later. 

> Cats have more than 3 whiskers?

Yes, see:

Broughton, S. D. "On the use of the whiskers in feline and other animals." Lond Med Phys J 49 (1823): 397-398.
